- RELEASES.md
- src/main/java/nl/nn/testtool/Checkpoint.java
- src/main/java/nl/nn/testtool/Report.java
- src/main/java/nl/nn/testtool/TestTool.java
Having messages truncated while reports are being made (rather than all at once afterwards) allows the developer to get an accurate value for getEstimatedMemoryUsage() during the report's initialisation. In this case, for example (link to future pull request pending).
> Move truncate functionality

- RELEASES.md
- src/main/java/nl/nn/testtool/echo2/ComparePane.java
Since Echo2 doesn't support getting the browser screen width, the new position has been set to 960, 50% of the most commonly occurring screen width of 1920px.
> Make compare tabs equally wide

- RELEASES.md
- src/main/java/nl/nn/testtool/Report.java
- src/main/java/nl/nn/testtool/TestTool.java
When adding a checkpoint to a report, the report's estimated memory usage up to that point is checked against a maximum (default 100MB).
> Add memory usage limit for adding more checkpoints

- RELEASES.md
- src/main/java/nl/nn/testtool/Checkpoint.java
- src/main/java/nl/nn/testtool/Debugger.java
- src/main/java/nl/nn/testtool/Report.java
- src/main/java/nl/nn/testtool/TestTool.java
- src/main/java/nl/nn/testtool/echo2/ComparePane.java
- src/main/java/nl/nn/testtool/echo2/Echo2Application.java
- src/main/java/nl/nn/testtool/echo2/reports/CheckpointComponent.java
- src/main/java/nl/nn/testtool/echo2/reports/ReportComponent.java
- src/main/java/nl/nn/testtool/echo2/run/RunComponent.java
- src/main/java/nl/nn/testtool/run/ReportRunner.java
- src/main/java/nl/nn/testtool/run/RunResult.java
- src/main/java/nl/nn/testtool/util/CsvUtil.java
=== Part 1: "local" variables ===
A new bit of functionality that allows users to A) set variables for individual reports and B) generate a set of clone reports with variables based on an input CSV.
=== Part 2: "external" variables ===
A new bit of functionality that allows users to refer to a previously run report's run-result for input data. Currently, it is only possible to extract data from valid XML messages. The syntax is as follows:
${report(relative path to target report)/checkpoint(index of target checkpoint)/xpath(xpath expression that points to the desired data)}
Example:
${report(../Pipeline HelloWorld)/checkpoint(3)/xpath(test/result)}
The user refers to the 'Pipeline HelloWorld' report in the parent folder...
${report(./Pipeline …
> Add report parameterization

- src/main/java/nl/nn/testtool/echo2/TransformationWindow.java
When editing a report, it should now be possible to see all textfields and attributes without scrolling. (based on a default resolution of 1920x1080)
> Decrease transformation textfield height

- src/main/java/nl/nn/testtool/Report.java
- src/main/java/nl/nn/testtool/echo2/run/RunComponent.java
Accidentally cloning a report without having set any variables in the input message is likely to lead to frustration. As such, I've added a textfield to the clone window where the user is prompted to edit the input message before generating clones.
Additionally, I've disabled the option to clone multiple reports simultaneously - which would probably never be used anyways - to avoid unnecessarily complicated code.
> Add textfield for input message to clone window

- RELEASES.md
- src/main/java/nl/nn/testtool/Checkpoint.java
- src/main/java/nl/nn/testtool/echo2/reports/CheckpointComponent.java
- src/main/java/nl/nn/testtool/echo2/reports/ReportComponent.java
- src/main/java/nl/nn/testtool/echo2/util/Upload.java
- src/main/java/nl/nn/testtool/run/ReportRunner.java
- src/main/java/nl/nn/testtool/run/RunResult.java
- src/main/java/nl/nn/testtool/util/Import.java
- src/main/java/nl/nn/testtool/util/ImportResult.java
=== 1. More simple variable syntax ===
Old vs new:
${report(./Pipeline HelloWorld)/checkpoint(23)/xpath(results/result[1])}
${checkpoint(287#23).xpath(results/result[1])}
Rather than having to copy a pipeline's name and building a relative path around it, users will now be able to skip that step and head straight to copying the checkpoint index (now checkpoint UID), which contains the report's storageId and the checkpoint's index.
Additionally, when uploading a zip-bundle of reports including some that interact with each other, the Ladybug will now automatically update the variables referring to those reports with their new storageId.
=== 2. Allow referring to entire checkpoint messages ===
If the user needs the value of a sessionKey or param, they can use ${checkpoint(287#23)}, leaving …
> Simplify variable syntax

- RELEASES.md
- src/main/java/nl/nn/testtool/Checkpoint.java
- src/main/java/nl/nn/testtool/TestTool.java
- src/main/java/nl/nn/testtool/echo2/Echo2Application.java
- src/main/java/nl/nn/testtool/echo2/RunPane.java
- src/main/java/nl/nn/testtool/echo2/reports/CheckpointComponent.java
- src/main/java/nl/nn/testtool/echo2/reports/ReportsTreeCellRenderer.java
- src/main/java/nl/nn/testtool/echo2/run/RunComponent.java
A new window opened with a new button that allows the user to enable/disable certain views in the Test tab. So far:
**[  ] Show report storage IDs**
Whether the reports' storage IDs should be shown in the Test tab.
**[  ] Show checkpoint IDs**
Whether checkpoints' names in the Report view's tree renderer should be preceded by their index.
With this last change, we can afford to remove the 'checkpoint index' attribute label, which has been found to be confusing. The 'report storageId' attribute label would also be redundant.
> Add test tab options

- RELEASES.md
- src/main/java/nl/nn/testtool/echo2/run/RunComponent.java
The red/green result of a report run in the test tab currently updates the wrong label. This should fix that.
> Fix run result visibility

- src/main/java/nl/nn/testtool/Checkpoint.java
display formatted(yyyy-MM-dd HH:mm:ss.SSS) date,  instead of a date string like Sat Sep 12 08:16:27 CEST 2020
> Date to string conversion for checkpoint's message

- RELEASES.md
- src/main/java/nl/nn/testtool/storage/xml/Metadata.java
- src/main/java/nl/nn/testtool/storage/xml/MetadataHandler.java
- src/main/java/nl/nn/testtool/storage/xml/XmlStorage.java
- Simplifies MetadataHandler.importFromFile and move it to XmlStorage.readReportFromFile.
- Adapt Metadata.fromReport to use path, name and lastmodified from given files.
> Refactoring XmlStorage to fix unnecessary rewrite

- src/main/java/nl/nn/testtool/web/api/MetadataApi.java
The API call for metadata used to send String[], but it is now changed to objects which is more clear and neat. The report filter has also been fixed now.
> API: Send out refined objects instead of String[] for metadata call

- src/main/java/nl/nn/testtool/web/api/TestToolApi.java
The payload also now contains the index of the report that is requested, instead of the number of reports to return.
> Only return a single report when requesting reports in progress

- src/main/java/nl/nn/testtool/web/api/ReportApi.java
- src/main/java/nl/nn/testtool/web/api/RunApi.java
- The report also sends out XML so it can be combined.
- The result returns the original and the edited report (and their respective XML). It also sends whether the reportXML's are equal.
> Change the way report and result is returned by the API

- src/main/java/nl/nn/testtool/storage/proofofmigration/ProofOfMigrationStorage.java
De huidige query om de PoM metadata op te halen is erg duur, omdat hij niet goed te versnellen is met indices.
De voorgestelde doet het efficienter
> Improve pom metadata query performance

- src/main/java/nl/nn/testtool/filter/View.java
- src/main/java/nl/nn/testtool/storage/proofofmigration/ProofOfMigrationView.java
- src/main/java/nl/nn/testtool/web/ApiAuthorizationFilter.java
- src/main/java/nl/nn/testtool/web/api/TestToolApi.java
- The strategy of comparison in the compare tab is linked to the view.
- The default strategy of comparison for the PoM view is based on the checkpoint number.
- The default strategy of comparison for the other views is based on the path.
> Add ability to change the strategy of node linking

- pom.xml
- src/main/java/nl/nn/xmldecoder/finder/GenericArrayTypeImpl.java
- src/main/java/nl/nn/xmldecoder/finder/ParameterizedTypeImpl.java
Makes it possible to build using JDK11
> fix javadoc generating error caused by invalid html5-tags

- src/main/java/nl/nn/testtool/TestTool.java
- src/main/java/nl/nn/testtool/web/api/TestToolApi.java
in TestTool.java:
added a field to store the time it takes before ladybug-frontend should show a warning about a report being in progress for too long. (in milliseconds)
in TestToolApi.java:
get request for reports in progress threshold time field from TestTool
This is added for issue "Show reports in progress warning #361" in the ladybug-frontend project
> Added field in TestTool for the reports in progress threshold time and an API get request for this field.

- src/main/java/nl/nn/testtool/web/api/ReportApi.java
I tried to have the same URL path as we have for deleting specific reports, with query parameters omitted for deleting all reports. That way, you delete all reports when you intend to delete a specific report. I fixed that by introducing path component `all` for the path to delete all reports.
> Add delete all to report api

- src/main/java/nl/nn/testtool/web/api/MetadataApi.java
Needed for issue [290](https://github.com/wearefrank/ladybug-frontend/issues/290) of the ladybug frontend project.
Functionality for multiple filters was already present, but not correctly implemented as it would only accept one filter parameter from the getMetadataList GET request. Resulting in only the first filter to be sent to the api to work and all others would be ignored.
> Changed metadataApi class so it accepts multiple filters now

- src/main/java/nl/nn/testtool/web/api/MetadataApi.java
A small fix for the copyright year. I forgot to update it in the previous pull request.
> fix: copyright needed to be updated to 2024

- src/main/java/nl/nn/testtool/MetadataExtractor.java
- src/main/java/nl/nn/testtool/web/api/TestToolApi.java
Needed for issue [#291](https://github.com/wearefrank/ladybug-frontend/issues/291)
Adds an extra field in the testtool/views/ GET request that gives the types of the different fields currently being used by reports.
ex. correlationId: string, storageId:int, etc.
> Metadata type definition for the TestToolApi

- src/main/java/nl/nn/testtool/filter/View.java
- src/main/java/nl/nn/testtool/web/api/TestToolApi.java
Reset the getViews endpoint back to how it was because an issue occured where calling `view.getDebugStorage().getName()` resulted in a different value than when calling `debugStorage().getName()` from inside of the view class.
> fix: storage name in view

- src/main/java/nl/nn/testtool/web/api/ReportApi.java
- src/main/java/nl/nn/testtool/web/api/TestToolApi.java
Changed the updateReport endpoint to allow updating report stub strategy.
Add new endpoint to get stub strategies
> feat: report level stub strategy can be updated

- src/main/java/nl/nn/testtool/storage/database/DatabaseStorage.java
- src/main/java/nl/nn/testtool/storage/database/DbmsSupport.java
- src/main/resources/ladybug/DatabaseChangelog_Debug.xml
Remove EnableTransactionManagement annotation.
When using bytea in PostgreSQL you no longer need a transactionmanager.
Removed sql hints when using mssql. These no longer seem to work.
I have changed the Liquibase script, so if people are using this it will break 😢 
The OptionalTransactionManager may be removed after this pr.
Closes https://github.com/frankframework/frankframework/pull/6824 and https://github.com/frankframework/frankframework/pull/6764.
> Remove EnableTransactionManagement annotation

- src/main/java/nl/nn/testtool/Report.java
- src/main/java/nl/nn/testtool/storage/Storage.java
- src/main/java/nl/nn/testtool/storage/database/DatabaseStorage.java
Added `isCrudStorage` method to storage interface, which is added to the report so the frontend knows if the report is from a readonly storage.
> Feat: add crud storage boolean to storage and report

- src/main/java/nl/nn/testtool/metadata/SessionKeyMetadataFieldExtractor.java
- src/test/java/nl/nn/testtool/metadata/SessionKeyMetadataFieldExtractorTest.java
These changes refactor the metadata extraction function to return null when no regex match is found.
> fix: return default value when no match is found
